version: "3.7"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your-database
      MYSQL_USER: your-username
      MYSQL_PASSWORD: your-password
      TZ: Asia/Bangkok
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php_api
    restart: unless-stopped
    environment:
      TZ: Asia/Bangkok
    volumes:
      - ./api:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "1111:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
    ports:
      - "1112:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
